function [state1,state2] = set_parameters(WindVelocity,InitPosition1, InitVelocity1,InitEuler1, InitPQR1, InitPosition2, InitVelocity2,InitEuler2, InitPQR2, state1, state2)
state1.Environment.WindVelocity = WindVelocity;
state1.XN = InitPosition1(1);
state1.XE = InitPosition1(2);
state1.XD = InitPosition1(3);
state1.U = InitVelocity1(1);
state1.V = InitVelocity1(2);
state1.W = InitVelocity1(3);
state1.Phi = InitEuler1(1);
state1.Theta = InitEuler1(2);
state1.Psi = InitEuler1(3);
state1.P = InitPQR1(1);
state1.Q = InitPQR1(2);
state1.R = InitPQR1(3);

state2.Environment.WindVelocity = WindVelocity;
state2.XN = InitPosition2(1);
state2.XE = InitPosition2(2);
state2.XD = InitPosition2(3);
state2.U = InitVelocity2(1);
state2.V = InitVelocity2(2);
state2.W = InitVelocity2(3);
state2.Phi = InitEuler2(1);
state2.Theta = InitEuler2(2);
state2.Psi = InitEuler2(3);
state2.P = InitPQR2(1);
state2.Q = InitPQR2(2);
state2.R = InitPQR2(3);
end